version: '3.7'

services:
  ## Front-end Service##
  front:
    image: mayconliborio/prime-security-front
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: ['yarn', 'serve']